---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
  - name: Stat venv1
    stat:
      path: /tmp/venv_1/bin/python
    register: venv_1

  - name: Check venv1 was created
    assert:
      that: venv_1.stat.executable
